#!/bin/bash -e

#
# Launch an instance that does the basic layer67 functionality:
#
# * Provides the world-facing instances that are hardened, fast and
#   have all the features you expect in a 2018 stack.
#
#
#
#
# run-instance --key-name="HQ" --security-group_ids="sg-85e1e9f1" --subnet-id="subnet-3644707d" --ip="10.91.0.250"
#
#

dev_acct_num="$(echo $JSAWS_AWS_ACCTS | egrep -o 'dev:[0-9]+' | cut -d':' -f2)"

my_mac0="$(curl -sS 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/' | head -1)"
my_ip="$(curl -sS 'http://169.254.169.254/latest/meta-data/local-ipv4')"
my_classb="$(echo $my_ip | cut -d'.' -f2)"
my_subnet_id="$(curl -sS "http://169.254.169.254/latest/meta-data/network/interfaces/macs/${my_mac0}/subnet-id")"

ndX="$NAMESPACE"
[[ -z $nsX ]] && nsX="peach"
acctX="$dev_acct_num"

instance_type="c5.large"
key_name="mario_demo"
security_group_ids="sg-915eb6e6"
user_data="file://${userdata_file}"
ip="10.${my_classb}.3.9"
subnet_id="$my_subnet_id"
count=1

eval "$(cli-shezargs $@)"

[[ -z $acct   ]] && acct="$acctX"
[[ -z $ns     ]] && ns="$nsX"

if [[ -z $iam_instance_profile ]]; then
  [[ -n $ns ]] && iam_instance_profile="Arn=arn:aws:iam::${acct}:instance-profile/${ns}-web-instance-role"
fi

wait_for_start() {
  local start="$SECONDS"

  echo -n "wait for start |${1}| whoami"
  while ! sshix -o ConnectTimeout=5 ${1} whoami; do
    sleep 1
    echo -n '.'
  done

  echo " -- Starting took: $(($SECONDS - $start)) seconds"
  sleep 1
}

#push_cert_to_server() {
#  message="$1"
#  fullpath="$2"
#  ip="$3"
#
#  printf "push_cert_to_server %-14s %-20s %-60s" "$message" "$ip" "$fullpath"
#
#  if [[ -n $fullpath ]]; then
#    ra invoke "$(fnn ~/dev 'crypto-kms\.js$')" pushCertToServer --ip=$ip --fullpath=$fullpath > /tmp/push-cert-to-server.json 2> /tmp/push-cert-to-server-error
#    cat /tmp/push-cert-to-server.json | jq -r '.items[].size' || true
#  else
#    echo ""
#  fi
#}

# =========================================================================================
announce " Launching instance"
# =========================================================================================

rm -f /tmp/run-instance-result.json

# ----- Create a temp user-data file -----
userdata_src="$(realpath ${scripts_dir}/data/userdata1)"
userdata_file="$(mktemp)"

cat  $userdata_src | head -1   > $userdata_file
echo "export MCFLY=marty"     >> $userdata_file
tail -n +2 $userdata_src      >> $userdata_file

if [[ -n $ssh_443 ]]; then
  echo "perl -pi -e 's/^#?Port 22$/Port 443/' /etc/ssh/sshd_config"     >> $userdata_file
  echo "service sshd restart || service ssh restart"                    >> $userdata_file
fi

# ----- Figure out the build number -----

rm -f /tmp/amis.json
aws ec2 describe-images --owners "$dev_acct_num" > /tmp/amis.json
build_num="$(cat /tmp/amis.json | jq -r '.Images[].Name' | egrep 'layer67-base-' | cut -d- -f3 | sort -n | tail -1)"
echo "build_num: $build_num"

image_id="$(cat /tmp/amis.json | jq -r --arg x "layer67-base-${build_num}" '.Images[] | select( .Name | contains($x)) | .ImageId')"
echo "image_id: $image_id"

# ----- Determine the sub-ips -----
octets123="$(echo $ip | cut -d'.' -f1-3)"
octet4="$(echo $ip | cut -d'.' -f4)"

security_group_ids="$(echo $security_group_ids | tr ',' ' ')"

if [[ $profile == prod ]]; then
  assumed_acct="pub"
  use_profile="--profile=prod"
fi

# ---------- Fire up the new instance ----------

[[ -z $stack    ]] && die "Need --stack="
[[ -z $tier     ]] && die "Need --tier="

rm -f /tmp/run-instance-result.json
ra invoke "$(fnn ~/dev 'layer67/lib/ec2Instance\.js')" runInstances --name="peach-${stack}-${tier}" > /tmp/run-instance-result.json

# The result JSON will be one line on error: '{}'
[[ $(cat /tmp/run-instance-result.json | jq . | wc -l) == 1 ]] && die


# Figure out what IP we ended up with
ip="$(cat /tmp/run-instance-result.json | jq -r '.Instances[].PrivateIpAddress')"
instance_id="$(cat /tmp/run-instance-result.json | jq -r '.Instances[].InstanceId')"

ip_for_filename="$(echo $ip | tr '.' '-')"
uniq_log_filename="/tmp/run-instance-result-${ip_for_filename}.json"
cp  "/tmp/run-instance-result.json" "$uniq_log_filename"

wait_for_start $ip

# ---------- Once the instance is started, finalize it to work ----------

#agent_ip="$(curl 'http://169.254.169.254/latest/meta-data/local-ipv4')"

# Tell new instance its identity
env_color="${color}"
[[ -z ${env_color}  ]] && env_color="black"

sshix $ip "local/scripts/01-bootstrap --setenv NAMESPACE $ns"
sshix $ip "local/scripts/01-bootstrap --setenv L67_COLOR ${env_color}"
sshix $ip "local/scripts/01-bootstrap --setenv L67_TIER  ${tier}"

sshix $ip "local/scripts/01-bootstrap --setenv L67_STACK ${stack}"
if [[ ${stack} == prod ]]; then
  sshix $ip "local/scripts/01-bootstrap --setenv NODE_ENV production"
fi

sshix $ip "cd ~/dev/layer67 && git pull"

#push-changes-to $ip
if [[ -n $pause ]]; then
  echo "Instance $ip is up"
  echo " push-changes-to $ip"
  echo ""
  read -n 1 -s -r -p "        Press any key to continue"
  echo
fi

sshix $ip "cd ~/dev/layer67 && npm install --production || true"
sshix $ip 'cd ~/dev/layer67 && pm2 start layer67.js --name agent -- agent --main --ip=$(curl -sS "http://169.254.169.254/latest/meta-data/local-ipv4")'

echo "Waiting to let instance start listening..."
sleep 5

# ---------- Fix /etc/hosts ----------
curl -sS "http://$ip:12340/etchosts?ip=10.12.21.4&name=redis"
curl -sS "http://$ip:12340/etchosts?ip=10.12.21.229&name=db"

# ----------- done -----------
echo ""
echo ""
echo " terminate-instances $use_profile $ip"
echo ""
echo "sshix $ip"


# Notes:

# 1. Build nginx conf files
# 2. Start the agent listener
# 3. Start the router
# 4. Signal that I am up
# 5. The master will push certs
# 6. Start nginx and be in business
#
# This command will cause the instance to listen for the FQDN, as the default server, and requiring
# client certificates. At startup, a list should be given.
#
# ra invoke lib/commands/configweb.js saveServerConfig --client-certs --default --fqdn=hq67.mobilewebassist.net
#
# * console.mobilewebassist.net.crt
# * console.mobilewebassist.net.key
# * console.mobilewebprint.net.crt
# * console.mobilewebprint.net.key
# * console.mobilewexprint.net.crt
# * console.mobilewexprint.net.key
# * hq.mobilewebassist.net.crt
# * hq.mobilewebassist.net.key
# *
# * mobilewebassist_root_client_ca.crt
# * mobilewebprint_root_client_ca.crt
# * mobilewexprint_root_client_ca.crt
#
# Then, the FQDN configs need to be scanned for certs they need. To this end, the confs have a built-in
# JSON object that can easily be found.
#
# cat /etc/nginx/sites-enabled/hq67.mobilewebassist.net.conf | egrep '# CONFIG_JSON ' | sed 's/^[^{[]*//g' | jq .
#
#
#
# Then those certs can be retrieved and un-encrypted:
#
# ra invoke  ../dev/layer67/lib/crypto-kms.js decrypt --base=mobilewebprint_root_client_ca.crt
#
#
#
# Then, those certs can be put to the instance:
#
# curl -sS 'http://10.13.1.9:12340/sudo/put/etc/nginx/asdf?chmod=640&chown=root' -F 'cfg.json=@/home/scotty/stmp/hq.mobilewebassist.net.crt' | jq .
#
#
#
#
#
#
#

