#!/bin/bash -e

eval "$(cli-shezargs $@)"

[[ -n $ip   ]] || die "Need --ip="
[[ -n $fqdn ]] || die "Need --fqdn="

if [[ $profile == prod ]]; then
  assumed_acct="pub"
fi

instance_id="$(sshix $ip 'curl -sS http://169.254.169.254/latest/meta-data/instance-id')"
eip="$(ra invoke "$(fn ~/dev/ ec2Instance\.js$)" eipForFqdn --fqdn="$fqdn" | jq -r '.eip')"

${scripts_dir}/aws-assumed-role "$assumed_acct" ec2 associate-address $use_profile --allocation-id=$eip --instance-id=$instance_id --private-ip-address=$ip --allow-reassociation
${scripts_dir}/aws-assumed-role "$assumed_acct" ec2 create-tags --resources "$instance_id" --tags "Key=Name,Value=$fqdn"

