#!/bin/bash -e

# TODO: use aws-assumed-role

eval "$(cli-shezargs $@)"

[[ -n $ip   ]] || die "Need --ip="
[[ -n $fqdn ]] || die "Need --fqdn="

if [[ $profile == prod ]]; then
  use_profile="--profile=sabuildout"
fi

instance_id="$(sshix $ip 'curl -sS http://169.254.169.254/latest/meta-data/instance-id')"
eip="$(ra invoke "$(fn ~/dev/ ec2Instance\.js$)" eipForFqdn --fqdn="$fqdn" | jq -r '.eip')"

aws ec2 associate-address $use_profile --allocation-id=$eip --instance-id=$instance_id --private-ip-address=$ip --allow-reassociation

