#!/bin/bash -e

#eval "$(cli-shezargs $@)"

acct="$1"
shift

#echo "awssts $acct" 1>&2

if [[ -n $acct ]]; then
  assumed_acct="$(echo $JSAWS_AWS_ACCT_EXTRA_CREDS | egrep -o 'pub:[^,]+' | cut -d':' -f2 | cut -d'/' -f1)"
  assumed_role="$(echo $JSAWS_AWS_ACCT_EXTRA_CREDS | egrep -o 'pub:[^,]+' | cut -d'/' -f2)"

  aws_sts=( $(aws sts assume-role --role-arn arn:aws:iam::${assumed_acct}:role/${assumed_role} --role-session-name ri --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --output text) )
  export AWS_ACCESS_KEY_ID="${aws_sts[0]}"
  export AWS_SECRET_ACCESS_KEY="${aws_sts[1]}"
  export AWS_SESSION_TOKEN="${aws_sts[2]}"
fi

#echo aws "$@" 1>&2
aws "$@"

