#!/bin/bash -e

eval "$(cli-shezargs $@)"

die "This script does not really work; use run-web-instance --stack=cluster..."

ns="$NAMESPACE"

[[ -z $ns       ]] && die "Need --namespace="
[[ -z $color    ]] && die "Need --color"

${scripts_dir}/launch/run-instance --stack=cluster --tier=web --color=$color "$@"



