#!/bin/bash -e

eval "$(cli-shezargs $@)"

ns="$NAMESPACE"

[[ -z $ns ]] && die "Need --namespace="

rel="dev"
if [[ $profile == prod ]]; then
  rel="prod"
fi

dynamoKey="$(json-switch-quotes "{'id':{'S':'${rel}-a-cluster-launchconfig'}}")"
${scripts_dir}/launch/run-instance "$(aws dynamodb get-item --table-name ${ns}clusterDb --key $dynamoKey | jq -r '.Item.cli.S')" "$@"


