#!/bin/bash -e

stack="cluster"
domain_name="mobiledevassist.net"

sconfig_client="&client_certs=1"
sconfig_https="&https=1"

eval "$(cli-shezargs $@)"

ns="$NAMESPACE"

[[ -z $ns     ]] && die "Need --namespace="
[[ -z $color  ]] && die "Need --color="
[[ -z $stack  ]] && die "Need --stack="

if [[ $stack == prod ]]; then
  assumed_acct="pub"
  domain_name="mobilewebassist.net"
fi

${scripts_dir}/launch/run-instance --stack=${stack} --tier=web --color=${color} "$@"

ip="$(cat /tmp/run-instance-result.json | jq -r '.Instances[].PrivateIpAddress')"
instance_id="$(cat /tmp/run-instance-result.json | jq -r '.Instances[].InstanceId')"

${scripts_dir}/aws-assumed-role "$assumed_acct" ec2 create-tags --resources "$instance_id" --tags "Key=color,Value=$color" "Key=stack,Value=${stack}"

# ---------- Configure nginx ----------

# Setup for the following FQDNs
curl -sS "http://$ip:12340/root-config"
curl -sS "http://$ip:12340/server-config?fqdn=l67console.${domain_name}&port=5778${sconfig_client}${sconfig_https}"
#curl -sS "http://$ip:12340/server-config?fqdn=l67xapi.${domain_name}&port=5778${sconfig_client}${sconfig_https}"
curl -sS "http://$ip:12340/server-config?fqdn=l67xapi.${domain_name}&port=5778&http=1"
curl -sS "http://$ip:12340/server-config?fqdn=l67hq.${domain_name}&port=5777${sconfig_https}"

# ---------- Get the nginx conf files ----------

# =======================================================================
# And push the needed certs
announce "Pushing certs to server"
# =======================================================================

# ----- l67console.mobilewebassist.net
curl -sS "http://$ip:12340/file/etc/nginx/sites-enabled/l67console.${domain_name}.conf" | egrep '# CONFIG_JSON ' | sed 's/^[^{[]*//g' > /tmp/config.json

push-cert-to-server "ssh_cert"      "$(cat /tmp/config.json | jq -r '.certfile')" "$ip"     || true
push-cert-to-server "ssh_key"       "$(cat /tmp/config.json | jq -r '.keyfile')" "$ip"      || true
push-cert-to-server "client_cert"   "$(cat /tmp/config.json | jq -r '.clientCert')" "$ip"   || true



# ----- l67hq.mobilewebassist.net
curl -sS "http://$ip:12340/file/etc/nginx/sites-enabled/l67hq.${domain_name}.conf" | egrep '# CONFIG_JSON ' | sed 's/^[^{[]*//g' > /tmp/config.json

push-cert-to-server "ssh_cert"      "$(cat /tmp/config.json | jq -r '.certfile')" "$ip"   || true
push-cert-to-server "ssh_key"       "$(cat /tmp/config.json | jq -r '.keyfile')" "$ip"    || true
push-cert-to-server "client_cert"   "$(cat /tmp/config.json | jq -r '.clientCert')" "$ip" || true


# Only start the server if the caller wants
if [[ -z $delay_finishing ]]; then
  ${scripts_dir}/run-final-hq-start-tasks --ip=${ip} --stack=${stack}
fi

