#!/bin/bash -e

eval "$(cli-shezargs $@)"

ns="$NAMESPACE"

[[ -z $ns     ]] && die "Need --namespace="
[[ -z $color  ]] && die "Need --color="
[[ -z $stack  ]] && die "Need --stack="

${scripts_dir}/launch/run-instance --stack=${stack} --tier=app --color=${color} "$@"



