#!/bin/bash -e

eval "$(cli-shezargs $@)"

ns="$NAMESPACE"

die "This script does not really work"

${scripts_dir}/launch/run-instance --stack=dev --tier=app "$@"

#dynamoKey="$(json-switch-quotes "{'id':{'S':'${rel}-a-admin-launchconfig'}}")"
#${scripts_dir}/launch/run-instance "$(aws dynamodb get-item --table-name ${ns}clusterDb --key $dynamoKey | jq -r '.Item.cli.S')" "$@"

