#!/bin/bash -e

eval "$(cli-shezargs $@)"

ns="$NAMESPACE"

[[ -z $ns ]] && die "Need --namespace="

${scripts_dir}/launch/run-instance --stack=dev --tier=web "$@"

#dynamoKey="$(json-switch-quotes "{'id':{'S':'${rel}-a-web-launchconfig'}}")"
#${scripts_dir}/launch/run-instance "$(aws dynamodb get-item --table-name ${ns}clusterDb --key $dynamoKey | jq -r '.Item.cli.S')" "$@"

