#!/bin/bash -e

stack="cluster"

eval "$(cli-shezargs $@)"

ns="$NAMESPACE"

[[ -z $ns     ]] && die "Need --namespace="
[[ -z $color  ]] && die "Need --color="
[[ -z $stack  ]] && die "Need --stack="

if [[ $stack == prod ]]; then
  assumed_acct="pub"
fi

${scripts_dir}/launch/run-instance --stack=${stack} --tier=web --color=${color} "$@"

ip="$(cat /tmp/run-instance-result.json | jq -r '.Instances[].PrivateIpAddress')"
instance_id="$(cat /tmp/run-instance-result.json | jq -r '.Instances[].InstanceId')"

${scripts_dir}/aws-assumed-role "$assumed_acct" ec2 create-tags --resources "$instance_id" --tags "Key=color,Value=$color"

# ---------- Configure nginx ----------

# Setup for the following FQDNs
curl -sS "http://$ip:12340/root-config"
curl -sS "http://$ip:12340/server-config?fqdn=l67console.mobilewebassist.net&port=5778&client_certs=1&https=1"
#curl -sS "http://$ip:12340/server-config?fqdn=l67xapi.mobilewebassist.net&port=5778&client_certs=1&https=1"
curl -sS "http://$ip:12340/server-config?fqdn=l67xapi.mobilewebassist.net&port=5778&http=1"
curl -sS "http://$ip:12340/server-config?fqdn=l67hq.mobilewebassist.net&port=5777&https=1"

# ---------- Get the nginx conf files ----------

# =======================================================================
# And push the needed certs
announce "Pushing certs to server"
# =======================================================================

# ----- l67console.mobilesebassist.net
curl -sS "http://$ip:12340/file/etc/nginx/sites-enabled/l67console.mobilewebassist.net.conf" | egrep '# CONFIG_JSON ' | sed 's/^[^{[]*//g' > /tmp/config.json

push-cert-to-server "ssh_cert"      "$(cat /tmp/config.json | jq -r '.certfile')" "$ip"     || true
push-cert-to-server "ssh_key"       "$(cat /tmp/config.json | jq -r '.keyfile')" "$ip"      || true
push-cert-to-server "client_cert"   "$(cat /tmp/config.json | jq -r '.clientCert')" "$ip"   || true



# ----- l67hq.mobilewebassist.net
curl -sS "http://$ip:12340/file/etc/nginx/sites-enabled/l67hq.mobilewebassist.net.conf" | egrep '# CONFIG_JSON ' | sed 's/^[^{[]*//g' > /tmp/config.json

push-cert-to-server "ssh_cert"      "$(cat /tmp/config.json | jq -r '.certfile')" "$ip"   || true
push-cert-to-server "ssh_key"       "$(cat /tmp/config.json | jq -r '.keyfile')" "$ip"    || true
push-cert-to-server "client_cert"   "$(cat /tmp/config.json | jq -r '.clientCert')" "$ip" || true

# ---------- Once you want to assign the FQDN, it would be this ----------
#${scripts_dir}/../assign-fqdn --fqdn=l67hq.mobilewebassist.net --ip=${ip}


# Only start the server if the caller wants
if [[ -z $delay_finishing ]]; then
  ${scripts_dir}/run-final-hq-start-tasks --ip=${ip}
fi

