#!/bin/bash -e

eval "$(cli-shezargs $@)"

rel="dev"
if [[ $profile == prod ]]; then
  rel="prod"
fi

dynamoKey="$(json-switch-quotes "{'id':{'S':'${rel}-a-admin-launchconfig'}}")"
${scripts_dir}/launch/run-instance "$(aws dynamodb get-item --table-name peachclusterDb --key $dynamoKey | jq -r '.Item.cli.S')" "$@"

