#!/bin/bash -e

#
# Terminates Instances by internal IP
#
#   terminate-instances 1.2.3.4 1.2.3.5 1.2.3.6
#
# 1. Logs into instance via ssh, to run the z01-pre-terminate script.
# 2. Gets the instance-id (by ssh to the instance and getting instance-data), and
#    uses AWS cli to terminate by instance-id
#

eval "$(cli-shezargs $@)"

if [[ $profile == prod ]]; then
  assumed_acct="pub"
fi

for ip in "$@"; do
  echo "--- $ip"
  sshix $ip '[[ -f build-scripts/on-instance/z01-pre-terminate ]] && build-scripts/on-instance/z01-pre-terminate || true'
done

for ip in "$@"; do
  echo "--- $ip"
  instance_id="$(sshix $ip 'curl -sS http://169.254.169.254/latest/meta-data/instance-id')"

  ${scripts_dir}/aws-assumed-role "$assumed_acct" ec2 terminate-instances --instance-ids $instance_id

done

