#!/bin/bash -e

eval "$(cli-shezargs $@)"

[[ -z $ns      ]] && die "Need --ns="
[[ -z $classb  ]] && die "Need --classb="
[[ -z $rel     ]] && die "Need --rel="

acct="084075158741"
key_name="mario_demo"

subnet_public_a="subnet-70083b3b"
subnet_public_b="subnet-e17816bc"
subnet_public_c="subnet-995339b6"
subnet_public_d="subnet-cd3549f2"

subnet_app_a="subnet-77083b3c"
subnet_app_b="subnet-417c121c"
subnet_app_c="subnet-ffafc5d0"
subnet_app_d="subnet-79364a46"

sg_wide="sg-915eb6e6"
sg_web="sg-1643ab61"
sg_admin="sg-2745ad50"
sg_util="sg-7358b004"
sg_app="sg-f35bb384"

if [[ $rel == prod ]]; then
  acct="244406501905"
  key_name="mario_prod"

  subnet_public_a="subnet-e7a9c3c8"
  subnet_public_b="subnet-bef1c2f5"
  subnet_public_c="subnet-f49bbd90"
  subnet_public_d="subnet-d4265aeb"

  subnet_app_a="subnet-c3573dec"
  subnet_app_b="subnet-3c0c3f77"
  subnet_app_c="subnet-8d8aace9"
  subnet_app_d="subnet-c1334ffe"

  sg_wide="sg-c24aa2b5"
  sg_web="sg-1a52ba6d"
  sg_admin="sg-e459b193"
  sg_util="sg-1354bc64"
  sg_app="sg-4659b131"
fi

# Web tier
instance_profile="--iam-instance-profile=Arn=arn:aws:iam::${acct}:instance-profile/${ns}-web-instance-role"

lr put-cluster-db --ns=$ns --key=${rel}-a-web-launchconfig --set=cli="--key-name=$key_name --security-group-ids=${sg_web},${sg_wide} $instance_profile --ip=10.${classb}.0.10  --subnet-id=${subnet_public_a}"
lr put-cluster-db --ns=$ns --key=${rel}-b-web-launchconfig --set=cli="--key-name=$key_name --security-group-ids=${sg_web},${sg_wide} $instance_profile --ip=10.${classb}.4.10  --subnet-id=${subnet_public_b}"
lr put-cluster-db --ns=$ns --key=${rel}-c-web-launchconfig --set=cli="--key-name=$key_name --security-group-ids=${sg_web},${sg_wide} $instance_profile --ip=10.${classb}.8.10  --subnet-id=${subnet_public_c}"
lr put-cluster-db --ns=$ns --key=${rel}-d-web-launchconfig --set=cli="--key-name=$key_name --security-group-ids=${sg_web},${sg_wide} $instance_profile --ip=10.${classb}.12.10 --subnet-id=${subnet_public_d}"

# App tier
instance_profile="--iam-instance-profile=Arn=arn:aws:iam::${acct}:instance-profile/${ns}-app-instance-role"

lr put-cluster-db --ns=$ns --key=${rel}-a-app-launchconfig --set=cli="--key-name=$key_name --security-group-ids=${sg_app},${sg_wide} $instance_profile --ip=10.${classb}.16.32  --subnet-id=${subnet_app_a}"
lr put-cluster-db --ns=$ns --key=${rel}-b-app-launchconfig --set=cli="--key-name=$key_name --security-group-ids=${sg_app},${sg_wide} $instance_profile --ip=10.${classb}.32.32  --subnet-id=${subnet_app_b}"
lr put-cluster-db --ns=$ns --key=${rel}-c-app-launchconfig --set=cli="--key-name=$key_name --security-group-ids=${sg_app},${sg_wide} $instance_profile --ip=10.${classb}.48.32  --subnet-id=${subnet_app_c}"
lr put-cluster-db --ns=$ns --key=${rel}-d-app-launchconfig --set=cli="--key-name=$key_name --security-group-ids=${sg_app},${sg_wide} $instance_profile --ip=10.${classb}.64.32  --subnet-id=${subnet_app_d}"

# Admin tier
instance_profile="--iam-instance-profile=Arn=arn:aws:iam::${acct}:instance-profile/${ns}-admin-instance-role"

lr put-cluster-db --ns=$ns --key=${rel}-a-admin-launchconfig --set=cli="--key-name=HQ $instance_profile --security-group-ids=${sg_admin},${sg_wide} --ip=10.${classb}.0.250  --subnet-id=${subnet_public_a}"
lr put-cluster-db --ns=$ns --key=${rel}-b-admin-launchconfig --set=cli="--key-name=HQ $instance_profile --security-group-ids=${sg_admin},${sg_wide} --ip=10.${classb}.4.250  --subnet-id=${subnet_public_b}"
lr put-cluster-db --ns=$ns --key=${rel}-c-admin-launchconfig --set=cli="--key-name=HQ $instance_profile --security-group-ids=${sg_admin},${sg_wide} --ip=10.${classb}.8.250  --subnet-id=${subnet_public_c}"
lr put-cluster-db --ns=$ns --key=${rel}-d-admin-launchconfig --set=cli="--key-name=HQ $instance_profile --security-group-ids=${sg_admin},${sg_wide} --ip=10.${classb}.12.250  --subnet-id=${subnet_public_d}"

